// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:8556cd13-4481-4d46-8dd3-a53d9974d192",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_jxWHTqHTu",
    "aws_user_pools_web_client_id": "6k59arjh7jk679imgnrl24si9",
    "oauth": {},
    "aws_content_delivery_bucket": "appwebstore-20190907093327-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "us-west-2",
    "aws_content_delivery_url": "https://d2czrabrbhwz16.cloudfront.net"
};


export default awsmobile;
